"""empty message

Revision ID: 17616becb325
Revises: 
Create Date: 2020-02-18 16:58:54.431442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17616becb325'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bootcamps',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=80), nullable=True),
                    sa.Column('description', sa.String(
                        length=500), nullable=True),
                    sa.Column('website', sa.String(length=500), nullable=True),
                    sa.Column('phone', sa.String(length=80), nullable=True),
                    sa.Column('email', sa.String(length=80), nullable=True),
                    sa.Column('address', sa.String(length=120), nullable=True),
                    sa.Column('careers', sa.ARRAY(
                        sa.String(length=80)), nullable=True),
                    sa.Column('job_assistance', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('courses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=80), nullable=True),
                    sa.Column('description', sa.String(
                        length=500), nullable=True),
                    sa.Column('duration', sa.Integer(), nullable=True),
                    sa.Column('tuition', sa.Integer(), nullable=True),
                    sa.Column('minimum_skill', sa.String(
                        length=80), nullable=True),
                    sa.Column('scholarships_available',
                              sa.Boolean(), nullable=True),
                    sa.Column('bootcamp_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['bootcamp_id'], ['bootcamps.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    op.drop_table('bootcamps')
    # ### end Alembic commands ###
