[
    {
        "title": "Front End Web Development",
        "description": "This course will provide you with all of the essentials to become a successful frontend web developer. You will learn to master HTML, CSS and front end JavaScript, along with tools like Git, VSCode and front end frameworks like Vue",
        "weeks": 8,
        "tuition": 8000,
        "minimumSkill": "beginner",
        "scholarhips_available": True,
    },
    {
        "title": "Full Stack Web Development",
        "description": "In this course you will learn full stack web development, first learning all about the frontend with HTML/CSS/JS/Vue and then the backend with Node.js/Express/MongoDB",
        "weeks": 12,
        "tuition": 10000,
        "minimumSkill": "intermediate",
        "scholarships_available": True,
    },
    {
        "title": "Full Stack Web Dev",
        "description": "In this course you will learn all about the front end with HTML, CSS and JavaScript. You will master tools like Git and Webpack and also learn C# and ASP.NET with Postgres",
        "weeks": 10,
        "tuition": 12000,
        "minimumSkill": "intermediate",
        "scholarships_available": True,
    },
    {
        "title": "UI/UX",
        "description": "In this course you will learn to create beautiful interfaces. It is a mix of design and development to create modern user experiences on both web and mobile",
        "weeks": 12,
        "tuition": 10000,
        "minimumSkill": "intermediate",
        "scholarships_available": True,
    },
    {
        "title": "Web Design & Development",
        "description": "Get started building websites and web apps with HTML/CSS/JavaScript/PHP. We teach you",
        "weeks": 10,
        "tuition": 9000,
        "minimumSkill": "beginner",
        "scholarships_available": True,
    },
    {
        "title": "Data Science Program",
        "description": "In this course you will learn Python for data science, machine learning and big data tools",
        "weeks": 10,
        "tuition": 12000,
        "minimumSkill": "intermediate",
        "scholarships_available": False,
    },
    {
        "title": "Web Development",
        "description": "This course will teach you how to build high quality web applications with technologies like React, Node.js, PHP & Laravel",
        "weeks": 8,
        "tuition": 8000,
        "minimumSkill": "beginner",
        "scholarships_available": False,
    },
    {
        "title": "Software QA",
        "description": "This course will teach you everything you need to know about quality assurance",
        "weeks": 6,
        "tuition": 5000,
        "minimumSkill": "intermediate",
        "scholarships_available": False,
    },
    {
        "title": "IOS Development",
        "description": "Get started building mobile applications for IOS using Swift and other tools",
        "weeks": 8,
        "tuition": 6000,
        "minimumSkill": "intermediate",
        "scholarships_available": False,
    }
]
