"""empty message

Revision ID: ceb49541f20f
Revises: 17616becb325
Create Date: 2020-02-18 21:16:03.234764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb49541f20f'
down_revision = '17616becb325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bootcamps', sa.Column('img_url', sa.String(length=80), nullable=True))
    op.add_column('bootcamps', sa.Column('upvotes', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'upvotes')
    op.drop_column('bootcamps', 'upvotes')
    op.drop_column('bootcamps', 'img_url')
    # ### end Alembic commands ###
